### ISSUE TITLE
base64 decode error on new save-attachments code

### ISSUE THREAD

**Issue by PeterWagenaarNW** [SpamScope/mail-parser#47]
**Describe the bug**
If I use the new "save attachments" functionality of the command-line tool, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mailparser", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mailparser/__main__.py", line 260, in main
    write_attachments(parser.attachments, args.attachments_path)
  File "/usr/local/lib/python3.7/site-packages/mailparser/utils.py", line 518, in write_attachments
    filename=a["filename"],
  File "/usr/local/lib/python3.7/site-packages/mailparser/utils.py", line 540, in write_sample
    f.write(payload.decode("base64"))
AttributeError: 'str' object has no attribute 'decode'
```

**To Reproduce**

$ mkdir test
$ mailparser -sa -ap test -f test_email.MSG -o

**Expected behavior**
Tool puts attachments into "test" directory

**Raw mail**
Test email that reproduces the bug can be found at https://github.com/mattgwwalker/msg-extractor/blob/master/example-msg-files/unicode.msg

**Environment:**
 - OS: OSX
 - Docker: no
 - mail-parser version 3.8.0

**Additional context**
Because it's new code I figured it's probably easier for you to make a quick fix than for me to go through the trouble of making a pull request.

The problem can be fixed by changing 
https://github.com/SpamScope/mail-parser/blob/develop/mailparser/utils.py#L540

into:

```
            f.write(base64.b64decode(payload))
```

**Comment by PeterWagenaarNW** [comment]
Oh, it seems line 529 of the same file also has a decode error because of the same reason.

Changing ```                payload = i["payload"].decode("base64")``` to ```payload = base64.b64decode(i["payload])``` should fix it

**Comment by fedelemantuano** [comment]
Hi @PeterWagenaarNW,

thanks for your issue and resolution.
I've just release a new version: https://pypi.org/project/mail-parser/

**Comment by klwjan** [comment]
Hi, this issue still persists in the same file for the print_attachments() function at line 510. The line should be changed to` payload = base64.b64decode(i["payload])` as well.

**Comment by fedelemantuano** [comment]
Hi @klwjan,
I didn't have errors, but I accept your suggestion because it's more clean.

Thanks
